/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as StubsTravelRouteImport } from './routes/stubs.travel'
import { Route as StubsSupportRouteImport } from './routes/stubs.support'
import { Route as StubsMediaRouteImport } from './routes/stubs.media'
import { Route as StubsGarageRouteImport } from './routes/stubs.garage'
import { Route as RegistryTaxonomyRouteImport } from './routes/registry.taxonomy'
import { Route as RegistryKnowledgeRouteImport } from './routes/registry.knowledge'
import { Route as RegistryFederationRouteImport } from './routes/registry.federation'
import { Route as RegistryAiRouteImport } from './routes/registry.ai'
import { Route as ModulesModuleKeyRouteImport } from './routes/modules.$moduleKey'
import { Route as RegistryFieldsIndexRouteImport } from './routes/registry.fields.index'
import { Route as RegistryFieldsNewRouteImport } from './routes/registry.fields.new'
import { Route as RegistryFieldsLifecycleRouteImport } from './routes/registry.fields.lifecycle'
import { Route as RegistryFieldsFieldIdRouteImport } from './routes/registry.fields.$fieldId'
import { Route as ModulesModuleKeyFieldsRouteImport } from './routes/modules.$moduleKey.fields'
import { Route as RegistryFieldsFieldIdValuesRouteImport } from './routes/registry.fields.$fieldId.values'
import { Route as RegistryFieldsFieldIdVersionsVersionNoRouteImport } from './routes/registry.fields.$fieldId.versions.$versionNo'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StubsTravelRoute = StubsTravelRouteImport.update({
  id: '/stubs/travel',
  path: '/stubs/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const StubsSupportRoute = StubsSupportRouteImport.update({
  id: '/stubs/support',
  path: '/stubs/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StubsMediaRoute = StubsMediaRouteImport.update({
  id: '/stubs/media',
  path: '/stubs/media',
  getParentRoute: () => rootRouteImport,
} as any)
const StubsGarageRoute = StubsGarageRouteImport.update({
  id: '/stubs/garage',
  path: '/stubs/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryTaxonomyRoute = RegistryTaxonomyRouteImport.update({
  id: '/registry/taxonomy',
  path: '/registry/taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryKnowledgeRoute = RegistryKnowledgeRouteImport.update({
  id: '/registry/knowledge',
  path: '/registry/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryFederationRoute = RegistryFederationRouteImport.update({
  id: '/registry/federation',
  path: '/registry/federation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryAiRoute = RegistryAiRouteImport.update({
  id: '/registry/ai',
  path: '/registry/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleKeyRoute = ModulesModuleKeyRouteImport.update({
  id: '/$moduleKey',
  path: '/$moduleKey',
  getParentRoute: () => ModulesRoute,
} as any)
const RegistryFieldsIndexRoute = RegistryFieldsIndexRouteImport.update({
  id: '/registry/fields/',
  path: '/registry/fields/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryFieldsNewRoute = RegistryFieldsNewRouteImport.update({
  id: '/registry/fields/new',
  path: '/registry/fields/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryFieldsLifecycleRoute = RegistryFieldsLifecycleRouteImport.update({
  id: '/registry/fields/lifecycle',
  path: '/registry/fields/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryFieldsFieldIdRoute = RegistryFieldsFieldIdRouteImport.update({
  id: '/registry/fields/$fieldId',
  path: '/registry/fields/$fieldId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleKeyFieldsRoute = ModulesModuleKeyFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => ModulesModuleKeyRoute,
} as any)
const RegistryFieldsFieldIdValuesRoute =
  RegistryFieldsFieldIdValuesRouteImport.update({
    id: '/values',
    path: '/values',
    getParentRoute: () => RegistryFieldsFieldIdRoute,
  } as any)
const RegistryFieldsFieldIdVersionsVersionNoRoute =
  RegistryFieldsFieldIdVersionsVersionNoRouteImport.update({
    id: '/versions/$versionNo',
    path: '/versions/$versionNo',
    getParentRoute: () => RegistryFieldsFieldIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/decisions': typeof DecisionsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/modules': typeof ModulesRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/users': typeof UsersRoute
  '/modules/$moduleKey': typeof ModulesModuleKeyRouteWithChildren
  '/registry/ai': typeof RegistryAiRoute
  '/registry/federation': typeof RegistryFederationRoute
  '/registry/knowledge': typeof RegistryKnowledgeRoute
  '/registry/taxonomy': typeof RegistryTaxonomyRoute
  '/stubs/garage': typeof StubsGarageRoute
  '/stubs/media': typeof StubsMediaRoute
  '/stubs/support': typeof StubsSupportRoute
  '/stubs/travel': typeof StubsTravelRoute
  '/u/$username': typeof UUsernameRoute
  '/modules/$moduleKey/fields': typeof ModulesModuleKeyFieldsRoute
  '/registry/fields/$fieldId': typeof RegistryFieldsFieldIdRouteWithChildren
  '/registry/fields/lifecycle': typeof RegistryFieldsLifecycleRoute
  '/registry/fields/new': typeof RegistryFieldsNewRoute
  '/registry/fields/': typeof RegistryFieldsIndexRoute
  '/registry/fields/$fieldId/values': typeof RegistryFieldsFieldIdValuesRoute
  '/registry/fields/$fieldId/versions/$versionNo': typeof RegistryFieldsFieldIdVersionsVersionNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/decisions': typeof DecisionsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/modules': typeof ModulesRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/users': typeof UsersRoute
  '/modules/$moduleKey': typeof ModulesModuleKeyRouteWithChildren
  '/registry/ai': typeof RegistryAiRoute
  '/registry/federation': typeof RegistryFederationRoute
  '/registry/knowledge': typeof RegistryKnowledgeRoute
  '/registry/taxonomy': typeof RegistryTaxonomyRoute
  '/stubs/garage': typeof StubsGarageRoute
  '/stubs/media': typeof StubsMediaRoute
  '/stubs/support': typeof StubsSupportRoute
  '/stubs/travel': typeof StubsTravelRoute
  '/u/$username': typeof UUsernameRoute
  '/modules/$moduleKey/fields': typeof ModulesModuleKeyFieldsRoute
  '/registry/fields/$fieldId': typeof RegistryFieldsFieldIdRouteWithChildren
  '/registry/fields/lifecycle': typeof RegistryFieldsLifecycleRoute
  '/registry/fields/new': typeof RegistryFieldsNewRoute
  '/registry/fields': typeof RegistryFieldsIndexRoute
  '/registry/fields/$fieldId/values': typeof RegistryFieldsFieldIdValuesRoute
  '/registry/fields/$fieldId/versions/$versionNo': typeof RegistryFieldsFieldIdVersionsVersionNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/decisions': typeof DecisionsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/modules': typeof ModulesRouteWithChildren
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/users': typeof UsersRoute
  '/modules/$moduleKey': typeof ModulesModuleKeyRouteWithChildren
  '/registry/ai': typeof RegistryAiRoute
  '/registry/federation': typeof RegistryFederationRoute
  '/registry/knowledge': typeof RegistryKnowledgeRoute
  '/registry/taxonomy': typeof RegistryTaxonomyRoute
  '/stubs/garage': typeof StubsGarageRoute
  '/stubs/media': typeof StubsMediaRoute
  '/stubs/support': typeof StubsSupportRoute
  '/stubs/travel': typeof StubsTravelRoute
  '/u/$username': typeof UUsernameRoute
  '/modules/$moduleKey/fields': typeof ModulesModuleKeyFieldsRoute
  '/registry/fields/$fieldId': typeof RegistryFieldsFieldIdRouteWithChildren
  '/registry/fields/lifecycle': typeof RegistryFieldsLifecycleRoute
  '/registry/fields/new': typeof RegistryFieldsNewRoute
  '/registry/fields/': typeof RegistryFieldsIndexRoute
  '/registry/fields/$fieldId/values': typeof RegistryFieldsFieldIdValuesRoute
  '/registry/fields/$fieldId/versions/$versionNo': typeof RegistryFieldsFieldIdVersionsVersionNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/decisions'
    | '/login'
    | '/memory'
    | '/modules'
    | '/permissions'
    | '/profile'
    | '/roles'
    | '/users'
    | '/modules/$moduleKey'
    | '/registry/ai'
    | '/registry/federation'
    | '/registry/knowledge'
    | '/registry/taxonomy'
    | '/stubs/garage'
    | '/stubs/media'
    | '/stubs/support'
    | '/stubs/travel'
    | '/u/$username'
    | '/modules/$moduleKey/fields'
    | '/registry/fields/$fieldId'
    | '/registry/fields/lifecycle'
    | '/registry/fields/new'
    | '/registry/fields/'
    | '/registry/fields/$fieldId/values'
    | '/registry/fields/$fieldId/versions/$versionNo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/decisions'
    | '/login'
    | '/memory'
    | '/modules'
    | '/permissions'
    | '/profile'
    | '/roles'
    | '/users'
    | '/modules/$moduleKey'
    | '/registry/ai'
    | '/registry/federation'
    | '/registry/knowledge'
    | '/registry/taxonomy'
    | '/stubs/garage'
    | '/stubs/media'
    | '/stubs/support'
    | '/stubs/travel'
    | '/u/$username'
    | '/modules/$moduleKey/fields'
    | '/registry/fields/$fieldId'
    | '/registry/fields/lifecycle'
    | '/registry/fields/new'
    | '/registry/fields'
    | '/registry/fields/$fieldId/values'
    | '/registry/fields/$fieldId/versions/$versionNo'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/decisions'
    | '/login'
    | '/memory'
    | '/modules'
    | '/permissions'
    | '/profile'
    | '/roles'
    | '/users'
    | '/modules/$moduleKey'
    | '/registry/ai'
    | '/registry/federation'
    | '/registry/knowledge'
    | '/registry/taxonomy'
    | '/stubs/garage'
    | '/stubs/media'
    | '/stubs/support'
    | '/stubs/travel'
    | '/u/$username'
    | '/modules/$moduleKey/fields'
    | '/registry/fields/$fieldId'
    | '/registry/fields/lifecycle'
    | '/registry/fields/new'
    | '/registry/fields/'
    | '/registry/fields/$fieldId/values'
    | '/registry/fields/$fieldId/versions/$versionNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DecisionsRoute: typeof DecisionsRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  PermissionsRoute: typeof PermissionsRoute
  ProfileRoute: typeof ProfileRoute
  RolesRoute: typeof RolesRoute
  UsersRoute: typeof UsersRoute
  RegistryAiRoute: typeof RegistryAiRoute
  RegistryFederationRoute: typeof RegistryFederationRoute
  RegistryKnowledgeRoute: typeof RegistryKnowledgeRoute
  RegistryTaxonomyRoute: typeof RegistryTaxonomyRoute
  StubsGarageRoute: typeof StubsGarageRoute
  StubsMediaRoute: typeof StubsMediaRoute
  StubsSupportRoute: typeof StubsSupportRoute
  StubsTravelRoute: typeof StubsTravelRoute
  UUsernameRoute: typeof UUsernameRoute
  RegistryFieldsFieldIdRoute: typeof RegistryFieldsFieldIdRouteWithChildren
  RegistryFieldsLifecycleRoute: typeof RegistryFieldsLifecycleRoute
  RegistryFieldsNewRoute: typeof RegistryFieldsNewRoute
  RegistryFieldsIndexRoute: typeof RegistryFieldsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stubs/travel': {
      id: '/stubs/travel'
      path: '/stubs/travel'
      fullPath: '/stubs/travel'
      preLoaderRoute: typeof StubsTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stubs/support': {
      id: '/stubs/support'
      path: '/stubs/support'
      fullPath: '/stubs/support'
      preLoaderRoute: typeof StubsSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stubs/media': {
      id: '/stubs/media'
      path: '/stubs/media'
      fullPath: '/stubs/media'
      preLoaderRoute: typeof StubsMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stubs/garage': {
      id: '/stubs/garage'
      path: '/stubs/garage'
      fullPath: '/stubs/garage'
      preLoaderRoute: typeof StubsGarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/taxonomy': {
      id: '/registry/taxonomy'
      path: '/registry/taxonomy'
      fullPath: '/registry/taxonomy'
      preLoaderRoute: typeof RegistryTaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/knowledge': {
      id: '/registry/knowledge'
      path: '/registry/knowledge'
      fullPath: '/registry/knowledge'
      preLoaderRoute: typeof RegistryKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/federation': {
      id: '/registry/federation'
      path: '/registry/federation'
      fullPath: '/registry/federation'
      preLoaderRoute: typeof RegistryFederationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/ai': {
      id: '/registry/ai'
      path: '/registry/ai'
      fullPath: '/registry/ai'
      preLoaderRoute: typeof RegistryAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleKey': {
      id: '/modules/$moduleKey'
      path: '/$moduleKey'
      fullPath: '/modules/$moduleKey'
      preLoaderRoute: typeof ModulesModuleKeyRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/registry/fields/': {
      id: '/registry/fields/'
      path: '/registry/fields'
      fullPath: '/registry/fields/'
      preLoaderRoute: typeof RegistryFieldsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/fields/new': {
      id: '/registry/fields/new'
      path: '/registry/fields/new'
      fullPath: '/registry/fields/new'
      preLoaderRoute: typeof RegistryFieldsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/fields/lifecycle': {
      id: '/registry/fields/lifecycle'
      path: '/registry/fields/lifecycle'
      fullPath: '/registry/fields/lifecycle'
      preLoaderRoute: typeof RegistryFieldsLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/fields/$fieldId': {
      id: '/registry/fields/$fieldId'
      path: '/registry/fields/$fieldId'
      fullPath: '/registry/fields/$fieldId'
      preLoaderRoute: typeof RegistryFieldsFieldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleKey/fields': {
      id: '/modules/$moduleKey/fields'
      path: '/fields'
      fullPath: '/modules/$moduleKey/fields'
      preLoaderRoute: typeof ModulesModuleKeyFieldsRouteImport
      parentRoute: typeof ModulesModuleKeyRoute
    }
    '/registry/fields/$fieldId/values': {
      id: '/registry/fields/$fieldId/values'
      path: '/values'
      fullPath: '/registry/fields/$fieldId/values'
      preLoaderRoute: typeof RegistryFieldsFieldIdValuesRouteImport
      parentRoute: typeof RegistryFieldsFieldIdRoute
    }
    '/registry/fields/$fieldId/versions/$versionNo': {
      id: '/registry/fields/$fieldId/versions/$versionNo'
      path: '/versions/$versionNo'
      fullPath: '/registry/fields/$fieldId/versions/$versionNo'
      preLoaderRoute: typeof RegistryFieldsFieldIdVersionsVersionNoRouteImport
      parentRoute: typeof RegistryFieldsFieldIdRoute
    }
  }
}

interface ModulesModuleKeyRouteChildren {
  ModulesModuleKeyFieldsRoute: typeof ModulesModuleKeyFieldsRoute
}

const ModulesModuleKeyRouteChildren: ModulesModuleKeyRouteChildren = {
  ModulesModuleKeyFieldsRoute: ModulesModuleKeyFieldsRoute,
}

const ModulesModuleKeyRouteWithChildren =
  ModulesModuleKeyRoute._addFileChildren(ModulesModuleKeyRouteChildren)

interface ModulesRouteChildren {
  ModulesModuleKeyRoute: typeof ModulesModuleKeyRouteWithChildren
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesModuleKeyRoute: ModulesModuleKeyRouteWithChildren,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

interface RegistryFieldsFieldIdRouteChildren {
  RegistryFieldsFieldIdValuesRoute: typeof RegistryFieldsFieldIdValuesRoute
  RegistryFieldsFieldIdVersionsVersionNoRoute: typeof RegistryFieldsFieldIdVersionsVersionNoRoute
}

const RegistryFieldsFieldIdRouteChildren: RegistryFieldsFieldIdRouteChildren = {
  RegistryFieldsFieldIdValuesRoute: RegistryFieldsFieldIdValuesRoute,
  RegistryFieldsFieldIdVersionsVersionNoRoute:
    RegistryFieldsFieldIdVersionsVersionNoRoute,
}

const RegistryFieldsFieldIdRouteWithChildren =
  RegistryFieldsFieldIdRoute._addFileChildren(
    RegistryFieldsFieldIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DecisionsRoute: DecisionsRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  ModulesRoute: ModulesRouteWithChildren,
  PermissionsRoute: PermissionsRoute,
  ProfileRoute: ProfileRoute,
  RolesRoute: RolesRoute,
  UsersRoute: UsersRoute,
  RegistryAiRoute: RegistryAiRoute,
  RegistryFederationRoute: RegistryFederationRoute,
  RegistryKnowledgeRoute: RegistryKnowledgeRoute,
  RegistryTaxonomyRoute: RegistryTaxonomyRoute,
  StubsGarageRoute: StubsGarageRoute,
  StubsMediaRoute: StubsMediaRoute,
  StubsSupportRoute: StubsSupportRoute,
  StubsTravelRoute: StubsTravelRoute,
  UUsernameRoute: UUsernameRoute,
  RegistryFieldsFieldIdRoute: RegistryFieldsFieldIdRouteWithChildren,
  RegistryFieldsLifecycleRoute: RegistryFieldsLifecycleRoute,
  RegistryFieldsNewRoute: RegistryFieldsNewRoute,
  RegistryFieldsIndexRoute: RegistryFieldsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
